version: '1'

services:
  bot-trading:
    build: .
    container_name: bot-trading-container
    environment:
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
  
    restart: unless-stopped
